// Generated by wrangler types
interface CloudflareEnv {
  PHOTOS: R2Bucket;
  DB: D1Database;
  ASSETS: Fetcher;
  UPLOAD_TOKEN: string;
  ADMIN_EMAILS: string;
  ADMIN_PASSWORD_HASH: string;
  ADMIN_SESSION_SECRET: string;
  ADMIN_PATH: string;
  GTM_ID: string;
  ALLOW_INDEXING: string;
  OPINIONSYSTEM_API_KEY: string;
}
